name: Sample test action

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop

jobs:
  build:

    runs-on: macOS-latest
    steps:
    
      - name: Create directories
        run: |
          mkdir -p ~/ikura/results        
          mkdir -p ~/ikura/project
          
      - name: Navigate to project
        run: |
          cd ~/ikura/project
          
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: develop
          
      - name: Navigate to results
        run: |
          cd ~/ikura/results   
          
      - name: Checkout
        run: |
          git clone https://${{ secrets.API_TOKEN }}:dmaltsev@github.com/dmaltsev/gh-page-test
          cd gh-page-test
          echo "<h1>Hello World!</h1>" > index.html
          git add .
          git commit -m "Update"
          git push -u

          

