name: Sample test action

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop

jobs:
  build:

    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: develop
      
      - name: Push new files into repo
        run: |
          cd ../
          mkdir newData && cd newData
          git config credential.helper '!f(){echo username=token; echo "password=${{ secrets.API_TOKEN }}";};f'

