name: Sample test action

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop

jobs:
  build:

    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: develop
      
      - name: Push new files into repo
        run: |
          cd ../
          mkdir newData && cd newData
          git clone https://${{ secrets.API_TOKEN }}@github.com/dmaltsev/gh-page-test.git
          cd gh-page-test
          touch index.html
          echo "<h1>Hello world</h1>" > index.html
          git add .
          git commit -m "Update"
          git push
