name: Sample test action

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop

jobs:
  build:

    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: develop
      
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: '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'
        with:
          source-directory: 'output'
          destination-github-username: 'dmaltsev'
          destination-repository-name: 'gh-page-test'
          user-email: demaltsev@gmail.com
          target-branch: main
